-- Drop unused tables (already applied via MCP on 2026-03-12)
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS level_rules CASCADE;
DROP TABLE IF EXISTS unlocks CASCADE;
